- config.yml
depends on RMI-PACTA/pacta.data.preparation/pull/274
> update to most recent version of 2021Q4 masterdata_debt

- run_pacta_data_preparation.R
> explicitly drop groups in `summarise()`

- Dockerfile
see https://github.com/RMI-PACTA/pacta.data.preparation/issues/273#issuecomment-1494859234
> use dev version of {dbplyr} until fix is on CRAN

- run_pacta_data_preparation.R
closes #25 
depends on https://github.com/RMI-PACTA/pacta.data.scraping/issues/3
> use {pacta.data.scraping}

- run_pacta_data_preparation.R
depends on https://github.com/RMI-PACTA/pacta.data.preparation/pull/292
related https://github.com/RMI-PACTA/pacta.data.preparation/issues/275
> now that functions are exported, no need to namespace them

- config.yml
- run_pacta_data_preparation.R
closes #27 
depends on https://github.com/RMI-PACTA/workflow.prepare.pacta.indices/pull/21
> remove all of the indices prep

- config.yml
- run_pacta_data_preparation.R
related to https://github.com/RMI-PACTA/pacta.portfolio.analysis/pull/225
related to https://github.com/RMI-PACTA/pacta.portfolio.analysis/pull/227
related to https://github.com/RMI-PACTA/workflow.transition.monitor/pull/148
FYI: new dependencies are automatically picked up by https://github.com/RMI-PACTA/workflow.data.preparation/blob/d85172291ff299c511ff4a9632dd7ed298648542/Dockerfile#L12
> export SQLite versions of appropriate files

- Dockerfile
> handle cran and non-cran deps separately

- config.yml
- run_pacta_data_preparation.R
> Remove `additional years`

- run_pacta_data_preparation.R
> Load `tdm_delta_years` from config

- run_pacta_data_preparation.R
> Add log message for index scraping

- Dockerfile
> install system dependencies for {pacta.data.scraping} in Dockerfile

- config.yml
closes #36 
I think `time_horizon` is the only one we definitely should inherit... @jdhoffa ?
> inherit `time_horizon`

- run_pacta_data_preparation.R
> reuse list of relevant PACTA packages `pacta_packages`

- run_pacta_data_preparation.R
This will allow us to fail fast if HTTP requests fail.
> Shift scraping functionality prior to FactSet data pulling

- config.yml
AI has changed from using `Q4` to `q4`...
> fix typo in config

- README.md
> add instructions to README for running locally in RStudio

- run_pacta_data_preparation.R
> save `index_regions` to outputs

- config.yml
> document the config keys

- config.yml
- run_pacta_data_preparation.R
Adds config option to export archives of the data inputs and output directories, at same level of output directory (no nesting)
Closes: #152
Relates to #153
> feat(app): #152 Add functionality to export archives

- README.md
update Docker README section to reflect changes made to docker-compose.yml in #142
> update Docker README section to reflect changes to docker-compose.yml

- run_pacta_data_preparation.R
messed this up in a merge conflict in #168
> fix merge conflict with `pacta_financial_timestamp`

- README.md
> add badge to README

- run_pacta_data_preparation.R
Note: currently `threshold = 0` is used to maintain current behavior, though a more strict threshold is probably desirable
> utilize new `pacta.data.preparation::prepare_fund_data()` function

- run_pacta_data_preparation.R
> utilize new `pacta.data.preparation::prepare_isin_to_fund_table()` function

- run_pacta_data_preparation.R
> fix ISS emissions double counting

- run_pacta_data_preparation.R
> include the FactSet inputs' manifest in the outputs manifest

- run_pacta_data_preparation.R
- towards #94 
- depends on https://github.com/RMI-PACTA/pacta.data.preparation/pull/357
> use `pacta.data.preparation::determine_relevant_years()`

- run_pacta_data_preparation.R
- towards #94 
- depends on https://github.com/RMI-PACTA/pacta.data.preparation/pull/360
> Use `pacta.data.preparation::prepare_masterdata_debt()`

- run_pacta_data_preparation.R
- towards #94 
- depends on https://github.com/RMI-PACTA/pacta.data.preparation/pull/361
> use new ISS prep functions

- Dockerfile
> use PPM for package install

- DESCRIPTION
- README.md
- config.yml
- docker-compose.yml
- run_pacta_data_preparation.R
- depends on https://github.com/RMI-PACTA/pacta.scenario.data.preparation/pull/38
- depends on https://github.com/RMI-PACTA/pacta.scenario.data.preparation/pull/39
> adapt to new scenario inputs

- Dockerfile
- README.md
> use public `pacta.data.preparation`

- README.md
- config.yml
- docker-compose.yml
Update docs and config to reflect newly public `workflow.scenario.preparation`
> Update to use `workflow.scenario.preparation`

- config.yml
Update to latest version of 22Q4 scenario files.
> update 22q4 scenario data

- config.yml
Following https://github.com/RMI-PACTA/workflow.factset/pull/73 and database update for new ISINs.
> update path to new factset data

- config.yml
> update 23Q4 scenario timestamp for desktop config
