RMI-PACTA/workflow.data.preparation

run_pacta_data_preparation.R
closes #5
related ADO-6159
Copies the NEWS.md files from the relevant PACTA pkgs into the output directory so there is a human friendly record of the recent changes made in those pkgs.
=> copy in relevant NEWS files to outputs from relevant PACTA pkgs

config.yml, run_pacta_data_preparation.R
This PR:
* Adds a new parameter, `tdm_delta_years`, to the `config.yml`, which indicates any extra years that scenario targets need be calculated for, to be used in the TDM. These years are "deltas" meaning a duration, as measured from the start year (rather than a fixed value)
* Adds these new years to the `run_pacta_data_preparation` script
What this PR does NOT do: Test if those years are even present in any of the scenario data!!
Relates to https://github.com/RMI-PACTA/pacta.portfolio.analysis/issues/219
Closes #31
=> Add `tdm_years` concept to data preparation

config.yml
Currently, scenario targets are only calculated for years for which we have ABCD data. 
Since we only have data up until 2030, calculating targets for TDM for 2021, 2026 and 2031 won't work.
We also recently revised our decision for choosing an appropriate start year.
Beyond this, it is not in-line with what is described here: https://github.com/RMI-PACTA/pacta.interactive.report/blob/54b3ff30056e398c4dc33890b7194df69910b1f0/general_en_template/rmd/07-IPR.Rmd#L3
=> Update `tdm_delta_years` to be in bounds of ABCD data

run_pacta_data_preparation.R
This PR makes use of the newly defined `scenario_source_pacta_geography_bridge` to bridge the scenario-defined region names (e.g. IPR "WORLD") to the PACTA-compatible scenario name (e.g. "Global"). 
It does this using a dataset exported by the pacta.scenario.preparation package. 
Currently the only regions defined and managed are "Global", "OECD" and "NonOECD". 
The only scenarios this applies to are "ETP2020", "GECO2021", "ISF2021", "WEO2021", and "IPR2021".
Prior to adding new scenarios to Transition Monitor, we will need to update this list. 
Depends on https://github.com/RMI-PACTA/pacta.scenario.preparation/pull/91
=> Use new dataset `scenario_source_pacta_geography_bridge` to bridge scenario region names

run_pacta_data_preparation.R
This will always confuse me. But tidyselect prefers quoted names over the `.data` pronoun.
=> Remove deprecated use of `.data$` in tidyselect functions

config.yml
I will never understand this naming convention lol. 
Delivery date, and then uppercase with underscores, but then title case with spaces (but also an underscore?), and finally snakecase... then quarter
=> Include latest 2021Q4 AI data drop in config.yml

run_pacta_data_preparation.R
Fixes a bug that I introduced in https://github.com/RMI-PACTA/workflow.data.preparation/pull/53
=> Add missing `-` sign to call to `select()`

run_pacta_data_preparation.R
This PR:
* changes out the logging package from `{rlog}` to `{logger}`, 
* standardizes the format for string interpolation (using `{glue}` via `logger::formatter_glue()`)
* Cleans up the logging strings:
* End strings with a single `.`
* Quoting filenames
=> Change logging package, and clean logging strings

config.yml
I believe that we agreed to turn this on by default in a Tech Review call some weeks ago?
=> export SQLite files by default

DESCRIPTION
following the logic of [RMI-PACTA/workflow.transition.monitor/pull/231](https://github.com/RMI-PACTA/workflow.transition.monitor/pull/231), this PR adds a DESCRIPTION file to this repo.
Note: This *only* adds a DESCRIPTION file, it does not change the installation process of the [Dockerfile](https://github.com/RMI-PACTA/workflow.data.preparation/blob/main/Dockerfile).
=> add a DESCRIPTION file

DESCRIPTION, LICENSE, LICENSE.md
following the logic of [RMI-PACTA/workflow.transition.monitor/pull/232](https://github.com/RMI-PACTA/workflow.transition.monitor/pull/232), this PR does all the appropriate things related to adding a license to the repo, including:
- adding a LICENSE file
- adding a LICENSE.md file
- properly specifying the license in the DESCRIPTION file
=> add a license

workflow.data.preparation.Rproj
Because a DESCRIPTION file has been added to this repo, RStudio seems to insist on adding these build preferences to the .Rproj file. As far as I know, they are meaningless and won't cause any problems in this context, so I'm allowing them rather than constantly fighting them to keep my git history clean.
=> add build preferences to .Rproj file (because it insists)

DESCRIPTION
closes #105
To be honest, I don't fully understand why {dbplyr} is needed, but it appears that something in this code requires it...
https://github.com/RMI-PACTA/workflow.data.preparation/blob/c08b8fb5a139716997ae2c0e83a01757d51a9a2d/run_pacta_data_preparation.R#L687-L707
I have verified that adding it allows the Docker run with SQLite export to complete successfully (without the error).
=> add dbplyr dependency

README.md
Used to point to `AR2023Q4`, but since the inputs are now generalized to also include factset (and likely soon to include scenarios too), makes sense to just generalize it.
=> Generalize input pathname in `README.md`

Dockerfile
=> remove chrome install no longer needed for pacta.data.scraping

Dockerfile
=> determine and install dependencies with {pak}

Dockerfile
closes #109 
copy in only DESCRIPTION and .env before installing R packages
=> optimize Docker layers

Dockerfile
closes #103 
based on official suggestion by {pak} at https://pak.r-lib.org/reference/install.html#pre-built-binaries
=> installing pre-built binary versions of {pak} in Dockerfile

run_pacta_data_preparation.R
=> ensure the AI Company ID to Entity ID data has only distinct rows

run_pacta_data_preparation.R
closes #113 
to prevent `.env` from overriding/conflicting with the desired "desktop" config
=> skip reading `.env` when running in desktop mode

run_pacta_data_preparation.R
As a safety precaution, I think it makes sense to add the specified config name and the config as-is to the manifest file.
=> add config name and config to manifest

run_pacta_data_preparation.R
I believe we originally created these scenario CSVs to faithfully replicate the setup for the former data.prep process, but as far as I know these CSVs are not useful for anything once the current data.prep is completely. In this PR, I move that process further down and rather than export those intermediate files just process the in memory data objects.
@jdhoffa hope you can review this thoroughly and agree
=> avoid unnecessary intermediate scenario files

run_pacta_data_preparation.R
To avoid writing to the inputs directory, initially save the pre-flight currencies data to an in-memory object and only write it to the outputs directory.
supersedes #100
=> save currencies data only to output path

run_pacta_data_preparation.R
depends on #99 
This PR computes the FactSet timestamp/s from the filenames of all input FactSet data files, and adds that info to the manifest. Note that it would be possible to use FactSet data files from different timestamps... in which case all unique timestamps would be added to the manifest as an array. In the future, e.g. in #118, we could consider giving an error or warning if all of these timestamps do not match.
=> compute FactSet timestamp/s from filenames

.dockerignore
closes #128 
based on https://github.com/RMI-PACTA/workflow.pacta/blob/main/.dockerignore with the following differences
- allowing markdown files because I think it is reasonably relevant to have the license and README markdown files baked into the image along with the associated code
- excluding the `docker-compose.yml` because that's not relevant inside the image (and I wonder if in some cases it could be a security concern, e.g. if one did not want local path specifications to be revealed inside the image)
=> add `.dockerignore` file

docker-compose.yml
depends on #99 
not sure why this was being done since the repo gets permanently copied into the Docker image. @jdhoffa?
=> don't bind mount the repo directory that gets copied in

README.md, config.yml, run_pacta_data_preparation.R
depends on https://github.com/RMI-PACTA/workflow.factset/pull/39
should be done before https://github.com/RMI-PACTA/pacta.data.preparation/pull/335
This tells the workflow to use the `factset_issue_code_bridge` from the FactSet inputs rather than using `pacta.data.preparation::factset_issue_code_bridge` which is set to be deprecated/removed (https://github.com/RMI-PACTA/pacta.data.preparation/issues/321)
⚠️ in this PR, I have temporarily set the default 2022Q4 config `factset_issue_code_bridge_filename` to `test-from-fds-test-20240207-03-postgres_factset_issue_code_bridge.rds` (which was the first version of this new file that I have had access to) to facilitate testing/verifying that this PR works (similar to what has been done with the other FactSet filenames), but these default …
=> use new `factset_issue_code_bridge` from `workflow.factset`

config.yml
since we removed TDM, IPR scenario is no longer desired in the default 2022Q4 config (confirmed with @AlexAxthelm @NAYRA-HERRERA and Nicholas)
=> remove IPR from default 2022Q4 config

config.yml
to maintain the existing "2 newlines between config sets for a specific quarter" pattern
=> minor whitespace changes in config

DESCRIPTION, README.md, config.yml, run_pacta_data_preparation.R
must be coordinated with https://github.com/RMI-PACTA/pacta.data.preparation/pull/336
uses the same strategy as #130 did to add the new `factset_issue_code_bridge.rds`, however, this one is a bit more complicated because `pacta.data.preparation::prepare_entity_info()` used `pacta.data.preparation::factset_industry_map_bridge` internally. Because of that, I see no way of doing this without relying on https://github.com/RMI-PACTA/pacta.data.preparation/pull/336 which is also reliant on this PR, i.e. both this PR and https://github.com/RMI-PACTA/pacta.data.preparation/pull/336 should be coordinated to be merged at roughly the same time. The reason being that the function signature of `pacta.data.preparation::prepare_entity_info()` changes and it can no longer function properly without …
=> use new `factset_industry_map_bridge.rds` from `workflow.factset`

DESCRIPTION, README.md, config.yml, run_pacta_data_preparation.R
must be coordinated with https://github.com/RMI-PACTA/pacta.data.preparation/pull/338
uses the same strategy as #133 did to add the new `factset_industry_map_bridge.rds`, including the complicated process of modifying the function signature of `prepare_entity_info()` and all that flows from that, which necessitates coordination with the connected PR in pacta.data.preparation and a dev version bump
note: as was done with the `factset_industry_map_bridge`, I load the `factset_manual_pacta_sector_override.rds` in the "intermediary files" section of the script
This tells the workflow to use the new `factset_manual_pacta_sector_override.rds` from the FactSet inputs rather than using `pacta.data.preparation::factset_manual_pacta_sector_override` which is set to be deprecated/removed in …
=> use new `factset_manual_pacta_sector_override.rds` from `workflow.factset`

run_pacta_data_preparation.R
By forcing garbage collection after large objects are removed, significantly better memory management is achieved.
I don't relish doing this, but it works...
Before
After
=> force garbage collection after large objects are removed

.dockerignore
We may want to have a more elegant solution in the future (see discussion in #138), but this works for now to include git status in the manifest export.
Closes: #138
=> build(docker): #138 Allow .git in build context

config.yml
- removes timestamp specific values from "default" config
- moves context specific configs to set directory paths towards the top
- makes timestamp configs inherit directory paths from new "docker" config
note: #145 will "officialize" the 2022Q4 values
=> cleanup config

config.yml, docker-compose.yml
Change from /outputs to /mnt/outputs, to match structure defined in #142 and #145
No associated issue.
=> refactor(deploy): Harmonize docker mount points

config.yml, run_pacta_data_preparation.R
Changes in this PR export data from scraped sources to file, so that all sources for a dataset are captured, and the dataset can be recreated later.
By default, exports to data prep outputs path, but can be specified with `preflight_data_path`. Writing to the outputs path by default, since this matches current behavior, and we do not have a unified inputs path that we are currently using.
Closes: #148
=> feat(app): #148 Export data from scraped files

config.yml, run_pacta_data_preparation.R
create a unique directory for outputs, and warn if it already exists
Directory name includes both pacta timestamp (2022Q4), and creation date (approximately the time the process starts, within a few seconds if run as script).
Example: `/outputs/2022Q4_20240218T165613Z` rather than just `/outputs`
~Additionally, exports 2 `zip` archives: one of all the input files, and another of the contents of the outputs directory~ See #159 
Closes: #151
See Also: #152
=> feat(app): #151 Put outputs into unique timestamped directory

run_pacta_data_preparation.R
This was removed in #73 when the FactSet database pulling info was removed, but `ent_entity_affiliates_last_update` is still created above and its value/info is still worthwhile to have in the manifest.
=> include `ent_entity_affiliates_last_update` in manifest

config.yml
Update local docker config to match changes made to [docker-compose.yml](https://github.com/RMI-PACTA/workflow.data.preparation/blob/main/docker-compose.yml) in #142
Also set `2022Q4` config to inherit the `docker` config again (removed in #145). @AlexAxthelm this should not affect the `2022Q4_azure` because `2022Q4` will inherit the `docker` config, but when `2022Q4_azure` inherits `2022Q4` it will overwrite those paths from the `docker` config with the expected paths.
``` r
config::get(config = "docker")$factset_data_path
#> [1] "/mnt/factset-extracted"
config::get(config = "2022Q4")$factset_data_path
#> [1] "/mnt/factset-extracted"
config::get(config = "2022Q4_azure")$factset_data_path
#> [1] "/mnt/factset-extracted/factset-pacta_timestamp-20221231T000000Z_pulled-20240217T134528Z"
```
=> update paths for local docker context

Dockerfile
closes #173 
- moves `WORKDIR /workflow.data.preparation` up so we don't have to keep specifying it
- copies `.env` and `DESCRIPTION` simultaneously
- copies `.git/` separately because I can't figure out if/how to do a multi-copy including a sub-directory
- copies `config.yml` `run_pacta_data_preparation.R` simultaneously
should we also remove the explicit `.dockerignore` @AlexAxthelm?
=> copy only needed files to `/workflow.data.preparation/` in Docker image

run_pacta_data_preparation.R
=> utilize new, minor `pacta.data.preparation` functions

run_pacta_data_preparation.R
- towards #94 
- depends on https://github.com/RMI-PACTA/pacta.data.preparation/pull/359
=> use `pacta.data.preparation::standardize_asset_type_names()`

config.yml
Since exporting the archives is very expensive (time and memory), I'm setting this default to `FALSE` and explicitly opting-in for the azure configs (where it is generally desired).
=> default `export_archives` to `FALSE`

DESCRIPTION, run_pacta_data_preparation.R
closes #18
Most validation errors originally found (below) have been resolved. Validation of `financial_data` and `abcd_flags_equity` has been removed for now and will be added in the future.
investigation issues:
- https://github.com/RMI-PACTA/workflow.data.preparation/issues/196
- https://github.com/RMI-PACTA/workflow.data.preparation/issues/197
- https://github.com/RMI-PACTA/workflow.data.preparation/issues/198
- https://github.com/RMI-PACTA/workflow.data.preparation/issues/198
relevant fixes in pacta.data.validation:
- https://github.com/RMI-PACTA/pacta.data.validation/pull/65
- https://github.com/RMI-PACTA/pacta.data.validation/pull/66
- https://github.com/RMI-PACTA/pacta.data.validation/pull/67
- https://github.com/RMI-PACTA/pacta.data.validation/pull/68
relevant fix in …
=> implement `pacta.data.validation`

config.yml
The initial scenario preparation configuration bump that was committed in #236 and #237 pointed to a scenario preparation output that was missing crucial data. 
The data was missing due to a bug that was introduced in: https://github.com/RMI-PACTA/pacta.scenario.data.preparation/pull/61
and later solved by:
https://github.com/RMI-PACTA/pacta.scenario.data.preparation/pull/63
The new scenario preparation outputs, in the directory:  `2023Q4_20240701_T105302Z`
which can be found here: https://pactadatadev.file.core.windows.net/workflow-scenario-preparation-outputs/2023Q4_20240701_T105302Z
contain all the expected output datasets.
=> config: update 2023Q4 scenario preparation config path
